/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SmitheryRegistryError } from "./smitheryregistryerror.js";

export type ErrorTData = {
  error: string;
};

export class ErrorT extends SmitheryRegistryError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: ErrorTData;

  constructor(
    err: ErrorTData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "ErrorT";
  }
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    error: z.string(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
  .transform((v) => {
    return new ErrorT(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
