/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { SmitheryRegistryError } from "./smitheryregistryerror.js";

export type HealthErrorData = {
  error: string;
};

export class HealthError extends SmitheryRegistryError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: HealthErrorData;

  constructor(
    err: HealthErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "HealthError";
  }
}

/** @internal */
export const HealthError$inboundSchema: z.ZodType<
  HealthError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new HealthError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
