/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @smithery/registry SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx serversList.ts
 */

import { SmitheryRegistry } from "@smithery/registry";

const smitheryRegistry = new SmitheryRegistry({
  bearerAuth: process.env["SMITHERY_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await smitheryRegistry.list({
    q: "owner:mem0ai is:verified memory",
  });

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
