/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @smithery/registry SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx serviceHealthCheck.example.ts
 */

import { SmitheryRegistry } from "@smithery/registry";

const smitheryRegistry = new SmitheryRegistry({
  bearerAuth: process.env["SMITHERY_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await smitheryRegistry.service.healthCheck();

  console.log(result);
}

main().catch(console.error);
