import type { CoffeeShop } from "../shared/types.js";

export const coffeeShops: CoffeeShop[] = [
  {
    id: "tiong-bahru-bakery",
    name: "Tiong Bahru Bakery",
    coords: [103.8372, 1.2868],
    neighborhood: "Tiong Bahru",
    description: "French-inspired bakery cafe with excellent coffee and pastries in heritage shophouse.",
    specialty: "Flat White, Croissants",
    vibe: ["Cozy", "Artisanal", "European"],
    priceRange: "$$",
    rating: 4.6,
    instagram: "@tiongbahrubakery",
    thumbnail: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&auto=format&fit=crop",
    openHours: "8am - 6pm"
  },
  {
    id: "common-man-coffee",
    name: "Common Man Coffee Roasters",
    coords: [103.8245, 1.2790],
    neighborhood: "Robertson Quay",
    description: "Award-winning roastery with minimalist aesthetic and expertly crafted brews.",
    specialty: "Pour Over, Single Origin",
    vibe: ["Minimalist", "Professional", "Specialty"],
    priceRange: "$$",
    rating: 4.7,
    instagram: "@commonmancoffeeroasters",
    thumbnail: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&auto=format&fit=crop",
    openHours: "8am - 5pm"
  },
  {
    id: "nylon-coffee",
    name: "Nylon Coffee Roasters",
    coords: [103.8526, 1.3172],
    neighborhood: "Everton Park",
    description: "Pioneering third-wave roaster in an industrial HDB void deck setting.",
    specialty: "Filter Coffee, Cold Brew",
    vibe: ["Industrial", "Authentic", "Local"],
    priceRange: "$",
    rating: 4.8,
    instagram: "@nyloncoffeeroasters",
    thumbnail: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&auto=format&fit=crop",
    openHours: "9am - 6pm"
  },
  {
    id: "forty-hands",
    name: "Forty Hands",
    coords: [103.8390, 1.2855],
    neighborhood: "Tiong Bahru",
    description: "Neighborhood favorite with strong community vibe and consistent quality.",
    specialty: "Cappuccino, Brunch",
    vibe: ["Community", "Relaxed", "Friendly"],
    priceRange: "$$",
    rating: 4.5,
    instagram: "@fortyhandscoffee",
    thumbnail: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&auto=format&fit=crop",
    openHours: "8am - 10pm"
  },
  {
    id: "chye-seng-huat",
    name: "Chye Seng Huat Hardware",
    coords: [103.8565, 1.3128],
    neighborhood: "Lavender",
    description: "Restored hardware store turned cafe with Papa Palheta coffee.",
    specialty: "Espresso, Siphon Coffee",
    vibe: ["Heritage", "Spacious", "Instagram-worthy"],
    priceRange: "$$",
    rating: 4.4,
    instagram: "@cshcafe",
    thumbnail: "https://images.unsplash.com/photo-1453614512568-c4024d13c247?w=800&auto=format&fit=crop",
    openHours: "9am - 6pm"
  },
  {
    id: "apartment-coffee",
    name: "Apartment Coffee",
    coords: [103.8987, 1.2998],
    neighborhood: "Haji Lane",
    description: "Tiny third-floor hideaway with killer coffee in the heart of Arab Street.",
    specialty: "Latte Art, Affogato",
    vibe: ["Cozy", "Hidden", "Intimate"],
    priceRange: "$",
    rating: 4.6,
    instagram: "@apartmentcoffee",
    thumbnail: "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800&auto=format&fit=crop",
    openHours: "11am - 7pm"
  },
  {
    id: "homeground-coffee",
    name: "Homeground Coffee Roasters",
    coords: [103.8456, 1.2812],
    neighborhood: "Katong",
    description: "Multi-roaster concept serving beans from around the world.",
    specialty: "Guest Roasters, Aeropress",
    vibe: ["Eclectic", "Diverse", "Educational"],
    priceRange: "$$",
    rating: 4.5,
    instagram: "@homegroundcoffee",
    thumbnail: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&auto=format&fit=crop",
    openHours: "9am - 6pm"
  },
  {
    id: "sarnies",
    name: "Sarnies",
    coords: [103.8453, 1.3046],
    neighborhood: "Telok Ayer",
    description: "Aussie-style cafe serving excellent coffee and creative sandwiches.",
    specialty: "Piccolo, Long Black",
    vibe: ["Australian", "Brunch", "Vibrant"],
    priceRange: "$$",
    rating: 4.4,
    instagram: "@sarniessg",
    thumbnail: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=800&auto=format&fit=crop",
    openHours: "8am - 4pm"
  },
  {
    id: "curious-palette",
    name: "The Curious Palette",
    coords: [103.8245, 1.2795],
    neighborhood: "Duxton Hill",
    description: "Specialty coffee meets wine bar in a charming heritage shophouse.",
    specialty: "Chemex, V60",
    vibe: ["Sophisticated", "Evening", "Wine"],
    priceRange: "$$$",
    rating: 4.5,
    instagram: "@thecuriouspalette",
    thumbnail: "https://images.unsplash.com/photo-1559496417-e7f25c2c3680?w=800&auto=format&fit=crop",
    openHours: "10am - 11pm"
  },
  {
    id: "mellower-coffee",
    name: "Mellower Coffee",
    coords: [103.8198, 1.2812],
    neighborhood: "Alexandra",
    description: "Japanese-style kissaten with meticulous brewing and tranquil atmosphere.",
    specialty: "Hand-drip, Single Origin",
    vibe: ["Japanese", "Zen", "Quiet"],
    priceRange: "$$",
    rating: 4.7,
    instagram: "@mellowercoffee",
    thumbnail: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=800&auto=format&fit=crop",
    openHours: "10am - 7pm"
  },
  {
    id: "cata-coffee",
    name: "Cata Coffee",
    coords: [103.90, 1.31],
    neighborhood: "Macpherson",
    description: "Modern specialty roastery with focus on precision brewing and single-origin beans.",
    specialty: "Espresso, Pour Over",
    vibe: ["Contemporary", "Specialty", "Minimalist"],
    priceRange: "$$",
    rating: 4.6,
    instagram: "@catacoffe",
    thumbnail: "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=800&auto=format&fit=crop",
    openHours: "9am - 6pm"
  }
];

