/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeleteProfilesBySlugServersByConfigSlugRequest = {
  slug: string;
  configSlug: string;
};

/** @internal */
export type DeleteProfilesBySlugServersByConfigSlugRequest$Outbound = {
  slug: string;
  configSlug: string;
};

/** @internal */
export const DeleteProfilesBySlugServersByConfigSlugRequest$outboundSchema:
  z.ZodType<
    DeleteProfilesBySlugServersByConfigSlugRequest$Outbound,
    z.ZodTypeDef,
    DeleteProfilesBySlugServersByConfigSlugRequest
  > = z.object({
    slug: z.string(),
    configSlug: z.string(),
  });

export function deleteProfilesBySlugServersByConfigSlugRequestToJSON(
  deleteProfilesBySlugServersByConfigSlugRequest:
    DeleteProfilesBySlugServersByConfigSlugRequest,
): string {
  return JSON.stringify(
    DeleteProfilesBySlugServersByConfigSlugRequest$outboundSchema.parse(
      deleteProfilesBySlugServersByConfigSlugRequest,
    ),
  );
}
