/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetConfigStatusByIdRequest = {
  id: string;
};

/** @internal */
export type GetConfigStatusByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetConfigStatusByIdRequest$outboundSchema: z.ZodType<
  GetConfigStatusByIdRequest$Outbound,
  z.ZodTypeDef,
  GetConfigStatusByIdRequest
> = z.object({
  id: z.string(),
});

export function getConfigStatusByIdRequestToJSON(
  getConfigStatusByIdRequest: GetConfigStatusByIdRequest,
): string {
  return JSON.stringify(
    GetConfigStatusByIdRequest$outboundSchema.parse(getConfigStatusByIdRequest),
  );
}
