/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetConfigByIdRequest = {
  id: string;
};

/** @internal */
export type GetConfigByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetConfigByIdRequest$outboundSchema: z.ZodType<
  GetConfigByIdRequest$Outbound,
  z.ZodTypeDef,
  GetConfigByIdRequest
> = z.object({
  id: z.string(),
});

export function getConfigByIdRequestToJSON(
  getConfigByIdRequest: GetConfigByIdRequest,
): string {
  return JSON.stringify(
    GetConfigByIdRequest$outboundSchema.parse(getConfigByIdRequest),
  );
}
