/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetProfilesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export type GetProfilesRequest$Outbound = {
  page?: number | undefined;
  pageSize?: number | undefined;
};

/** @internal */
export const GetProfilesRequest$outboundSchema: z.ZodType<
  GetProfilesRequest$Outbound,
  z.ZodTypeDef,
  GetProfilesRequest
> = z.object({
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
});

export function getProfilesRequestToJSON(
  getProfilesRequest: GetProfilesRequest,
): string {
  return JSON.stringify(
    GetProfilesRequest$outboundSchema.parse(getProfilesRequest),
  );
}
