/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProfilesBySlugServersByConfigSlugRequest = {
  slug: string;
  configSlug: string;
};

/**
 * Server details
 */
export type GetProfilesBySlugServersByConfigSlugResponse = {
  slug: string;
  displayName: string;
  mcpUrl: string;
  description: string | null;
};

/** @internal */
export type GetProfilesBySlugServersByConfigSlugRequest$Outbound = {
  slug: string;
  configSlug: string;
};

/** @internal */
export const GetProfilesBySlugServersByConfigSlugRequest$outboundSchema:
  z.ZodType<
    GetProfilesBySlugServersByConfigSlugRequest$Outbound,
    z.ZodTypeDef,
    GetProfilesBySlugServersByConfigSlugRequest
  > = z.object({
    slug: z.string(),
    configSlug: z.string(),
  });

export function getProfilesBySlugServersByConfigSlugRequestToJSON(
  getProfilesBySlugServersByConfigSlugRequest:
    GetProfilesBySlugServersByConfigSlugRequest,
): string {
  return JSON.stringify(
    GetProfilesBySlugServersByConfigSlugRequest$outboundSchema.parse(
      getProfilesBySlugServersByConfigSlugRequest,
    ),
  );
}

/** @internal */
export const GetProfilesBySlugServersByConfigSlugResponse$inboundSchema:
  z.ZodType<
    GetProfilesBySlugServersByConfigSlugResponse,
    z.ZodTypeDef,
    unknown
  > = z.object({
    slug: z.string(),
    displayName: z.string(),
    mcpUrl: z.string(),
    description: z.nullable(z.string()),
  });

export function getProfilesBySlugServersByConfigSlugResponseFromJSON(
  jsonString: string,
): SafeParseResult<
  GetProfilesBySlugServersByConfigSlugResponse,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      GetProfilesBySlugServersByConfigSlugResponse$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'GetProfilesBySlugServersByConfigSlugResponse' from JSON`,
  );
}
