/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetProfilesBySlugServersRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  slug: string;
};

/** @internal */
export type GetProfilesBySlugServersRequest$Outbound = {
  page?: number | undefined;
  pageSize?: number | undefined;
  slug: string;
};

/** @internal */
export const GetProfilesBySlugServersRequest$outboundSchema: z.ZodType<
  GetProfilesBySlugServersRequest$Outbound,
  z.ZodTypeDef,
  GetProfilesBySlugServersRequest
> = z.object({
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  slug: z.string(),
});

export function getProfilesBySlugServersRequestToJSON(
  getProfilesBySlugServersRequest: GetProfilesBySlugServersRequest,
): string {
  return JSON.stringify(
    GetProfilesBySlugServersRequest$outboundSchema.parse(
      getProfilesBySlugServersRequest,
    ),
  );
}
