/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetServersByNamespaceByNameLogsRequest = {
  numberRootComponentsSchemasLogsQuery?: components.LogsQuery | undefined;
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
};

/** @internal */
export type GetServersByNamespaceByNameLogsRequest$Outbound = {
  "#/components/schemas/LogsQuery"?: components.LogsQuery$Outbound | undefined;
  namespace: string;
  name: string;
};

/** @internal */
export const GetServersByNamespaceByNameLogsRequest$outboundSchema: z.ZodType<
  GetServersByNamespaceByNameLogsRequest$Outbound,
  z.ZodTypeDef,
  GetServersByNamespaceByNameLogsRequest
> = z.object({
  numberRootComponentsSchemasLogsQuery: components.LogsQuery$outboundSchema
    .optional(),
  namespace: z.string().default(""),
  name: z.string(),
}).transform((v) => {
  return remap$(v, {
    numberRootComponentsSchemasLogsQuery: "#/components/schemas/LogsQuery",
  });
});

export function getServersByNamespaceByNameLogsRequestToJSON(
  getServersByNamespaceByNameLogsRequest:
    GetServersByNamespaceByNameLogsRequest,
): string {
  return JSON.stringify(
    GetServersByNamespaceByNameLogsRequest$outboundSchema.parse(
      getServersByNamespaceByNameLogsRequest,
    ),
  );
}
