/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByNamespaceByNameRequest = {
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
};

/** @internal */
export type GetServersByNamespaceByNameRequest$Outbound = {
  namespace: string;
  name: string;
};

/** @internal */
export const GetServersByNamespaceByNameRequest$outboundSchema: z.ZodType<
  GetServersByNamespaceByNameRequest$Outbound,
  z.ZodTypeDef,
  GetServersByNamespaceByNameRequest
> = z.object({
  namespace: z.string().default(""),
  name: z.string(),
});

export function getServersByNamespaceByNameRequestToJSON(
  getServersByNamespaceByNameRequest: GetServersByNamespaceByNameRequest,
): string {
  return JSON.stringify(
    GetServersByNamespaceByNameRequest$outboundSchema.parse(
      getServersByNamespaceByNameRequest,
    ),
  );
}
