/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByQualifiedNameDeploymentsByIdRequest = {
  qualifiedName: string;
  id: string;
};

/** @internal */
export type GetServersByQualifiedNameDeploymentsByIdRequest$Outbound = {
  qualifiedName: string;
  id: string;
};

/** @internal */
export const GetServersByQualifiedNameDeploymentsByIdRequest$outboundSchema:
  z.ZodType<
    GetServersByQualifiedNameDeploymentsByIdRequest$Outbound,
    z.ZodTypeDef,
    GetServersByQualifiedNameDeploymentsByIdRequest
  > = z.object({
    qualifiedName: z.string(),
    id: z.string(),
  });

export function getServersByQualifiedNameDeploymentsByIdRequestToJSON(
  getServersByQualifiedNameDeploymentsByIdRequest:
    GetServersByQualifiedNameDeploymentsByIdRequest,
): string {
  return JSON.stringify(
    GetServersByQualifiedNameDeploymentsByIdRequest$outboundSchema.parse(
      getServersByQualifiedNameDeploymentsByIdRequest,
    ),
  );
}
