/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByIdRequest = {
  id: string;
};

/** @internal */
export type GetServersByIdRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetServersByIdRequest$outboundSchema: z.ZodType<
  GetServersByIdRequest$Outbound,
  z.ZodTypeDef,
  GetServersByIdRequest
> = z.object({
  id: z.string(),
});

export function getServersByIdRequestToJSON(
  getServersByIdRequest: GetServersByIdRequest,
): string {
  return JSON.stringify(
    GetServersByIdRequest$outboundSchema.parse(getServersByIdRequest),
  );
}
