/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByQualifiedNameLogsRequest = {
  qualifiedName: string;
};

/** @internal */
export type GetServersByQualifiedNameLogsRequest$Outbound = {
  qualifiedName: string;
};

/** @internal */
export const GetServersByQualifiedNameLogsRequest$outboundSchema: z.ZodType<
  GetServersByQualifiedNameLogsRequest$Outbound,
  z.ZodTypeDef,
  GetServersByQualifiedNameLogsRequest
> = z.object({
  qualifiedName: z.string(),
});

export function getServersByQualifiedNameLogsRequestToJSON(
  getServersByQualifiedNameLogsRequest: GetServersByQualifiedNameLogsRequest,
): string {
  return JSON.stringify(
    GetServersByQualifiedNameLogsRequest$outboundSchema.parse(
      getServersByQualifiedNameLogsRequest,
    ),
  );
}
