/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByNamespaceByNameDeploymentsByIdRequest = {
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
  id: string;
};

/** @internal */
export type GetServersByNamespaceByNameDeploymentsByIdRequest$Outbound = {
  namespace: string;
  name: string;
  id: string;
};

/** @internal */
export const GetServersByNamespaceByNameDeploymentsByIdRequest$outboundSchema:
  z.ZodType<
    GetServersByNamespaceByNameDeploymentsByIdRequest$Outbound,
    z.ZodTypeDef,
    GetServersByNamespaceByNameDeploymentsByIdRequest
  > = z.object({
    namespace: z.string().default(""),
    name: z.string(),
    id: z.string(),
  });

export function getServersByNamespaceByNameDeploymentsByIdRequestToJSON(
  getServersByNamespaceByNameDeploymentsByIdRequest:
    GetServersByNamespaceByNameDeploymentsByIdRequest,
): string {
  return JSON.stringify(
    GetServersByNamespaceByNameDeploymentsByIdRequest$outboundSchema.parse(
      getServersByNamespaceByNameDeploymentsByIdRequest,
    ),
  );
}
