/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByQualifiedNameRequest = {
  qualifiedName: string;
};

/** @internal */
export type GetServersByQualifiedNameRequest$Outbound = {
  qualifiedName: string;
};

/** @internal */
export const GetServersByQualifiedNameRequest$outboundSchema: z.ZodType<
  GetServersByQualifiedNameRequest$Outbound,
  z.ZodTypeDef,
  GetServersByQualifiedNameRequest
> = z.object({
  qualifiedName: z.string(),
});

export function getServersByQualifiedNameRequestToJSON(
  getServersByQualifiedNameRequest: GetServersByQualifiedNameRequest,
): string {
  return JSON.stringify(
    GetServersByQualifiedNameRequest$outboundSchema.parse(
      getServersByQualifiedNameRequest,
    ),
  );
}
