/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByQualifiedNameDeploymentsRequest = {
  qualifiedName: string;
};

/** @internal */
export type GetServersByQualifiedNameDeploymentsRequest$Outbound = {
  qualifiedName: string;
};

/** @internal */
export const GetServersByQualifiedNameDeploymentsRequest$outboundSchema:
  z.ZodType<
    GetServersByQualifiedNameDeploymentsRequest$Outbound,
    z.ZodTypeDef,
    GetServersByQualifiedNameDeploymentsRequest
  > = z.object({
    qualifiedName: z.string(),
  });

export function getServersByQualifiedNameDeploymentsRequestToJSON(
  getServersByQualifiedNameDeploymentsRequest:
    GetServersByQualifiedNameDeploymentsRequest,
): string {
  return JSON.stringify(
    GetServersByQualifiedNameDeploymentsRequest$outboundSchema.parse(
      getServersByQualifiedNameDeploymentsRequest,
    ),
  );
}
