/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type GetServersByQualifiedNameLogsRequest = {
  numberRootComponentsSchemasLogsQuery?: components.LogsQuery | undefined;
  qualifiedName: string;
};

/** @internal */
export type GetServersByQualifiedNameLogsRequest$Outbound = {
  "#/components/schemas/LogsQuery"?: components.LogsQuery$Outbound | undefined;
  qualifiedName: string;
};

/** @internal */
export const GetServersByQualifiedNameLogsRequest$outboundSchema: z.ZodType<
  GetServersByQualifiedNameLogsRequest$Outbound,
  z.ZodTypeDef,
  GetServersByQualifiedNameLogsRequest
> = z.object({
  numberRootComponentsSchemasLogsQuery: components.LogsQuery$outboundSchema
    .optional(),
  qualifiedName: z.string(),
}).transform((v) => {
  return remap$(v, {
    numberRootComponentsSchemasLogsQuery: "#/components/schemas/LogsQuery",
  });
});

export function getServersByQualifiedNameLogsRequestToJSON(
  getServersByQualifiedNameLogsRequest: GetServersByQualifiedNameLogsRequest,
): string {
  return JSON.stringify(
    GetServersByQualifiedNameLogsRequest$outboundSchema.parse(
      getServersByQualifiedNameLogsRequest,
    ),
  );
}
