/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetServersByNamespaceByNameDeploymentsRequest = {
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
};

/** @internal */
export type GetServersByNamespaceByNameDeploymentsRequest$Outbound = {
  namespace: string;
  name: string;
};

/** @internal */
export const GetServersByNamespaceByNameDeploymentsRequest$outboundSchema:
  z.ZodType<
    GetServersByNamespaceByNameDeploymentsRequest$Outbound,
    z.ZodTypeDef,
    GetServersByNamespaceByNameDeploymentsRequest
  > = z.object({
    namespace: z.string().default(""),
    name: z.string(),
  });

export function getServersByNamespaceByNameDeploymentsRequestToJSON(
  getServersByNamespaceByNameDeploymentsRequest:
    GetServersByNamespaceByNameDeploymentsRequest,
): string {
  return JSON.stringify(
    GetServersByNamespaceByNameDeploymentsRequest$outboundSchema.parse(
      getServersByNamespaceByNameDeploymentsRequest,
    ),
  );
}
