/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetServersRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  q?: string | undefined;
  profile?: string | undefined;
};

export type GetServersResponse = {
  result: components.ServersListResponse;
};

/** @internal */
export type GetServersRequest$Outbound = {
  page?: number | undefined;
  pageSize?: number | undefined;
  q?: string | undefined;
  profile?: string | undefined;
};

/** @internal */
export const GetServersRequest$outboundSchema: z.ZodType<
  GetServersRequest$Outbound,
  z.ZodTypeDef,
  GetServersRequest
> = z.object({
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  q: z.string().optional(),
  profile: z.string().optional(),
});

export function getServersRequestToJSON(
  getServersRequest: GetServersRequest,
): string {
  return JSON.stringify(
    GetServersRequest$outboundSchema.parse(getServersRequest),
  );
}

/** @internal */
export const GetServersResponse$inboundSchema: z.ZodType<
  GetServersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Result: components.ServersListResponse$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "Result": "result",
  });
});

export function getServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetServersResponse' from JSON`,
  );
}
