/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostServersByNamespaceByNameDeploymentsByIdResumeRequest = {
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
  id: string;
};

/** @internal */
export type PostServersByNamespaceByNameDeploymentsByIdResumeRequest$Outbound =
  {
    namespace: string;
    name: string;
    id: string;
  };

/** @internal */
export const PostServersByNamespaceByNameDeploymentsByIdResumeRequest$outboundSchema:
  z.ZodType<
    PostServersByNamespaceByNameDeploymentsByIdResumeRequest$Outbound,
    z.ZodTypeDef,
    PostServersByNamespaceByNameDeploymentsByIdResumeRequest
  > = z.object({
    namespace: z.string().default(""),
    name: z.string(),
    id: z.string(),
  });

export function postServersByNamespaceByNameDeploymentsByIdResumeRequestToJSON(
  postServersByNamespaceByNameDeploymentsByIdResumeRequest:
    PostServersByNamespaceByNameDeploymentsByIdResumeRequest,
): string {
  return JSON.stringify(
    PostServersByNamespaceByNameDeploymentsByIdResumeRequest$outboundSchema
      .parse(postServersByNamespaceByNameDeploymentsByIdResumeRequest),
  );
}
