/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PostServersByQualifiedNameDeploymentsByIdResumeRequest = {
  qualifiedName: string;
  id: string;
};

/** @internal */
export type PostServersByQualifiedNameDeploymentsByIdResumeRequest$Outbound = {
  qualifiedName: string;
  id: string;
};

/** @internal */
export const PostServersByQualifiedNameDeploymentsByIdResumeRequest$outboundSchema:
  z.ZodType<
    PostServersByQualifiedNameDeploymentsByIdResumeRequest$Outbound,
    z.ZodTypeDef,
    PostServersByQualifiedNameDeploymentsByIdResumeRequest
  > = z.object({
    qualifiedName: z.string(),
    id: z.string(),
  });

export function postServersByQualifiedNameDeploymentsByIdResumeRequestToJSON(
  postServersByQualifiedNameDeploymentsByIdResumeRequest:
    PostServersByQualifiedNameDeploymentsByIdResumeRequest,
): string {
  return JSON.stringify(
    PostServersByQualifiedNameDeploymentsByIdResumeRequest$outboundSchema.parse(
      postServersByQualifiedNameDeploymentsByIdResumeRequest,
    ),
  );
}
