/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Tokens = {
  accessToken: string;
  idToken?: string | undefined;
  tokenType: string;
  expiresIn?: number | undefined;
  scope?: string | undefined;
  refreshToken?: string | undefined;
};

export type Client = {
  clientId: string;
  clientSecret?: string | undefined;
  clientIdIssuedAt?: number | undefined;
  clientSecretExpiresAt?: number | undefined;
};

export type OauthData = {
  tokens: Tokens;
  client: Client;
};

export type PostProfilesBySlugServersRequestBody = {
  slug?: string | undefined;
  serverQualifiedName?: string | undefined;
  mcpUrl?: string | undefined;
  displayName?: string | undefined;
  configData?: any | undefined;
  oauthData?: OauthData | undefined;
};

export type PostProfilesBySlugServersRequest = {
  slug: string;
  requestBody?: PostProfilesBySlugServersRequestBody | undefined;
};

/**
 * Server created
 */
export type PostProfilesBySlugServersResponse = {
  slug: string;
  displayName: string;
  mcpUrl: string;
  description: string | null;
};

/** @internal */
export type Tokens$Outbound = {
  access_token: string;
  id_token?: string | undefined;
  token_type: string;
  expires_in?: number | undefined;
  scope?: string | undefined;
  refresh_token?: string | undefined;
};

/** @internal */
export const Tokens$outboundSchema: z.ZodType<
  Tokens$Outbound,
  z.ZodTypeDef,
  Tokens
> = z.object({
  accessToken: z.string(),
  idToken: z.string().optional(),
  tokenType: z.string(),
  expiresIn: z.number().optional(),
  scope: z.string().optional(),
  refreshToken: z.string().optional(),
}).transform((v) => {
  return remap$(v, {
    accessToken: "access_token",
    idToken: "id_token",
    tokenType: "token_type",
    expiresIn: "expires_in",
    refreshToken: "refresh_token",
  });
});

export function tokensToJSON(tokens: Tokens): string {
  return JSON.stringify(Tokens$outboundSchema.parse(tokens));
}

/** @internal */
export type Client$Outbound = {
  client_id: string;
  client_secret?: string | undefined;
  client_id_issued_at?: number | undefined;
  client_secret_expires_at?: number | undefined;
};

/** @internal */
export const Client$outboundSchema: z.ZodType<
  Client$Outbound,
  z.ZodTypeDef,
  Client
> = z.object({
  clientId: z.string(),
  clientSecret: z.string().optional(),
  clientIdIssuedAt: z.number().optional(),
  clientSecretExpiresAt: z.number().optional(),
}).transform((v) => {
  return remap$(v, {
    clientId: "client_id",
    clientSecret: "client_secret",
    clientIdIssuedAt: "client_id_issued_at",
    clientSecretExpiresAt: "client_secret_expires_at",
  });
});

export function clientToJSON(client: Client): string {
  return JSON.stringify(Client$outboundSchema.parse(client));
}

/** @internal */
export type OauthData$Outbound = {
  tokens: Tokens$Outbound;
  client: Client$Outbound;
};

/** @internal */
export const OauthData$outboundSchema: z.ZodType<
  OauthData$Outbound,
  z.ZodTypeDef,
  OauthData
> = z.object({
  tokens: z.lazy(() => Tokens$outboundSchema),
  client: z.lazy(() => Client$outboundSchema),
});

export function oauthDataToJSON(oauthData: OauthData): string {
  return JSON.stringify(OauthData$outboundSchema.parse(oauthData));
}

/** @internal */
export type PostProfilesBySlugServersRequestBody$Outbound = {
  slug?: string | undefined;
  serverQualifiedName?: string | undefined;
  mcpUrl?: string | undefined;
  displayName?: string | undefined;
  configData?: any | undefined;
  oauthData?: OauthData$Outbound | undefined;
};

/** @internal */
export const PostProfilesBySlugServersRequestBody$outboundSchema: z.ZodType<
  PostProfilesBySlugServersRequestBody$Outbound,
  z.ZodTypeDef,
  PostProfilesBySlugServersRequestBody
> = z.object({
  slug: z.string().optional(),
  serverQualifiedName: z.string().optional(),
  mcpUrl: z.string().optional(),
  displayName: z.string().optional(),
  configData: z.any().optional(),
  oauthData: z.lazy(() => OauthData$outboundSchema).optional(),
});

export function postProfilesBySlugServersRequestBodyToJSON(
  postProfilesBySlugServersRequestBody: PostProfilesBySlugServersRequestBody,
): string {
  return JSON.stringify(
    PostProfilesBySlugServersRequestBody$outboundSchema.parse(
      postProfilesBySlugServersRequestBody,
    ),
  );
}

/** @internal */
export type PostProfilesBySlugServersRequest$Outbound = {
  slug: string;
  RequestBody?: PostProfilesBySlugServersRequestBody$Outbound | undefined;
};

/** @internal */
export const PostProfilesBySlugServersRequest$outboundSchema: z.ZodType<
  PostProfilesBySlugServersRequest$Outbound,
  z.ZodTypeDef,
  PostProfilesBySlugServersRequest
> = z.object({
  slug: z.string(),
  requestBody: z.lazy(() => PostProfilesBySlugServersRequestBody$outboundSchema)
    .optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function postProfilesBySlugServersRequestToJSON(
  postProfilesBySlugServersRequest: PostProfilesBySlugServersRequest,
): string {
  return JSON.stringify(
    PostProfilesBySlugServersRequest$outboundSchema.parse(
      postProfilesBySlugServersRequest,
    ),
  );
}

/** @internal */
export const PostProfilesBySlugServersResponse$inboundSchema: z.ZodType<
  PostProfilesBySlugServersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
  displayName: z.string(),
  mcpUrl: z.string(),
  description: z.nullable(z.string()),
});

export function postProfilesBySlugServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostProfilesBySlugServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostProfilesBySlugServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostProfilesBySlugServersResponse' from JSON`,
  );
}
