/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type PostServersByIdRequest = {
  id: string;
  configRequest?: components.ConfigRequest | undefined;
};

/** @internal */
export type PostServersByIdRequest$Outbound = {
  id: string;
  ConfigRequest?: components.ConfigRequest$Outbound | undefined;
};

/** @internal */
export const PostServersByIdRequest$outboundSchema: z.ZodType<
  PostServersByIdRequest$Outbound,
  z.ZodTypeDef,
  PostServersByIdRequest
> = z.object({
  id: z.string(),
  configRequest: components.ConfigRequest$outboundSchema.optional(),
}).transform((v) => {
  return remap$(v, {
    configRequest: "ConfigRequest",
  });
});

export function postServersByIdRequestToJSON(
  postServersByIdRequest: PostServersByIdRequest,
): string {
  return JSON.stringify(
    PostServersByIdRequest$outboundSchema.parse(postServersByIdRequest),
  );
}
