/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type PutConfigByIdRequest = {
  id: string;
  saveUserConfigRequest?: components.SaveUserConfigRequest | undefined;
};

/** @internal */
export type PutConfigByIdRequest$Outbound = {
  id: string;
  SaveUserConfigRequest?: components.SaveUserConfigRequest$Outbound | undefined;
};

/** @internal */
export const PutConfigByIdRequest$outboundSchema: z.ZodType<
  PutConfigByIdRequest$Outbound,
  z.ZodTypeDef,
  PutConfigByIdRequest
> = z.object({
  id: z.string(),
  saveUserConfigRequest: components.SaveUserConfigRequest$outboundSchema
    .optional(),
}).transform((v) => {
  return remap$(v, {
    saveUserConfigRequest: "SaveUserConfigRequest",
  });
});

export function putConfigByIdRequestToJSON(
  putConfigByIdRequest: PutConfigByIdRequest,
): string {
  return JSON.stringify(
    PutConfigByIdRequest$outboundSchema.parse(putConfigByIdRequest),
  );
}
