/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type PutServersByNamespaceByNameDeploymentsRequest = {
  /**
   * Server namespace (optional, leave empty for unnamespaced servers)
   */
  namespace?: string | undefined;
  name: string;
  deployRequest?: components.DeployRequest | undefined;
};

/** @internal */
export type PutServersByNamespaceByNameDeploymentsRequest$Outbound = {
  namespace: string;
  name: string;
  DeployRequest?: components.DeployRequest$Outbound | undefined;
};

/** @internal */
export const PutServersByNamespaceByNameDeploymentsRequest$outboundSchema:
  z.ZodType<
    PutServersByNamespaceByNameDeploymentsRequest$Outbound,
    z.ZodTypeDef,
    PutServersByNamespaceByNameDeploymentsRequest
  > = z.object({
    namespace: z.string().default(""),
    name: z.string(),
    deployRequest: components.DeployRequest$outboundSchema.optional(),
  }).transform((v) => {
    return remap$(v, {
      deployRequest: "DeployRequest",
    });
  });

export function putServersByNamespaceByNameDeploymentsRequestToJSON(
  putServersByNamespaceByNameDeploymentsRequest:
    PutServersByNamespaceByNameDeploymentsRequest,
): string {
  return JSON.stringify(
    PutServersByNamespaceByNameDeploymentsRequest$outboundSchema.parse(
      putServersByNamespaceByNameDeploymentsRequest,
    ),
  );
}
