/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type PutServersByQualifiedNameDeploymentsRequest = {
  qualifiedName: string;
};

/** @internal */
export type PutServersByQualifiedNameDeploymentsRequest$Outbound = {
  qualifiedName: string;
};

/** @internal */
export const PutServersByQualifiedNameDeploymentsRequest$outboundSchema:
  z.ZodType<
    PutServersByQualifiedNameDeploymentsRequest$Outbound,
    z.ZodTypeDef,
    PutServersByQualifiedNameDeploymentsRequest
  > = z.object({
    qualifiedName: z.string(),
  });

export function putServersByQualifiedNameDeploymentsRequestToJSON(
  putServersByQualifiedNameDeploymentsRequest:
    PutServersByQualifiedNameDeploymentsRequest,
): string {
  return JSON.stringify(
    PutServersByQualifiedNameDeploymentsRequest$outboundSchema.parse(
      putServersByQualifiedNameDeploymentsRequest,
    ),
  );
}
