/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Result = {
  command: string;
  args: Array<string>;
  env?: { [k: string]: string } | undefined;
};

export type ConfigResponse = {
  success: boolean;
  result: Result;
};

/** @internal */
export const Result$inboundSchema: z.ZodType<Result, z.ZodTypeDef, unknown> = z
  .object({
    command: z.string(),
    args: z.array(z.string()),
    env: z.record(z.string()).optional(),
  });

export function resultFromJSON(
  jsonString: string,
): SafeParseResult<Result, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Result$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Result' from JSON`,
  );
}

/** @internal */
export const ConfigResponse$inboundSchema: z.ZodType<
  ConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  result: z.lazy(() => Result$inboundSchema),
});

export function configResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigResponse' from JSON`,
  );
}
