/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ConfigValidationResponse = {
  isComplete: boolean;
  hasExistingConfig: boolean;
  missingFields: Array<string>;
  fieldSchemas: { [k: string]: any };
};

/** @internal */
export const ConfigValidationResponse$inboundSchema: z.ZodType<
  ConfigValidationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  isComplete: z.boolean(),
  hasExistingConfig: z.boolean(),
  missingFields: z.array(z.string()),
  fieldSchemas: z.record(z.any()),
});

export function configValidationResponseFromJSON(
  jsonString: string,
): SafeParseResult<ConfigValidationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ConfigValidationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ConfigValidationResponse' from JSON`,
  );
}
