/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The type of server to instantiate
 */
export const ConnectionType = {
  Stdio: "stdio",
} as const;
/**
 * The type of server to instantiate
 */
export type ConnectionType = ClosedEnum<typeof ConnectionType>;

export type ConfigRequest = {
  /**
   * User performing the request
   */
  userId?: string | undefined;
  /**
   * The type of server to instantiate
   */
  connectionType: ConnectionType;
  /**
   * The configuration for the server
   */
  config: { [k: string]: any };
};

/** @internal */
export const ConnectionType$outboundSchema: z.ZodNativeEnum<
  typeof ConnectionType
> = z.nativeEnum(ConnectionType);

/** @internal */
export type ConfigRequest$Outbound = {
  userId?: string | undefined;
  connectionType: string;
  config: { [k: string]: any };
};

/** @internal */
export const ConfigRequest$outboundSchema: z.ZodType<
  ConfigRequest$Outbound,
  z.ZodTypeDef,
  ConfigRequest
> = z.object({
  userId: z.string().optional(),
  connectionType: ConnectionType$outboundSchema,
  config: z.record(z.any()),
});

export function configRequestToJSON(configRequest: ConfigRequest): string {
  return JSON.stringify(ConfigRequest$outboundSchema.parse(configRequest));
}
