/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type DeployRequest = {
  /**
   * JSON string of DeployPayload
   */
  payload: string;
  /**
   * JavaScript module content (for hosted deployments)
   */
  module?: string | undefined;
  /**
   * Source map content
   */
  sourcemap?: string | undefined;
};

/** @internal */
export type DeployRequest$Outbound = {
  payload: string;
  module?: string | undefined;
  sourcemap?: string | undefined;
};

/** @internal */
export const DeployRequest$outboundSchema: z.ZodType<
  DeployRequest$Outbound,
  z.ZodTypeDef,
  DeployRequest
> = z.object({
  payload: z.string(),
  module: z.string().optional(),
  sourcemap: z.string().optional(),
});

export function deployRequestToJSON(deployRequest: DeployRequest): string {
  return JSON.stringify(DeployRequest$outboundSchema.parse(deployRequest));
}
