/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentList = {
  id: string;
  status: string;
  mcpUrl?: string | undefined;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const DeploymentList$inboundSchema: z.ZodType<
  DeploymentList,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  status: z.string(),
  mcpUrl: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export function deploymentListFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentList' from JSON`,
  );
}
