/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeploymentLogEntry,
  DeploymentLogEntry$inboundSchema,
} from "./deploymentlogentry.js";

export type DeploymentInfo = {
  id: string;
  status: string;
  logs?: Array<DeploymentLogEntry> | undefined;
  mcpUrl?: string | undefined;
  createdAt: string;
  updatedAt: string;
};

/** @internal */
export const DeploymentInfo$inboundSchema: z.ZodType<
  DeploymentInfo,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  status: z.string(),
  logs: z.array(DeploymentLogEntry$inboundSchema).optional(),
  mcpUrl: z.string().optional(),
  createdAt: z.string(),
  updatedAt: z.string(),
});

export function deploymentInfoFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentInfo' from JSON`,
  );
}
