/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeployResponse = {
  deploymentId: string;
  status: string;
  mcpUrl: string;
  warnings?: Array<string> | undefined;
};

/** @internal */
export const DeployResponse$inboundSchema: z.ZodType<
  DeployResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  deploymentId: z.string(),
  status: z.string(),
  mcpUrl: z.string(),
  warnings: z.array(z.string()).optional(),
});

export function deployResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeployResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeployResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeployResponse' from JSON`,
  );
}
