/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentInfo = {};

/** @internal */
export const DeploymentInfo$inboundSchema: z.ZodType<
  DeploymentInfo,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function deploymentInfoFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentInfo' from JSON`,
  );
}
