/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  DeploymentLogEntryError,
  DeploymentLogEntryError$inboundSchema,
} from "./deploymentlogentryerror.js";

export const Stage = {
  Deploy: "deploy",
  Scan: "scan",
  Metadata: "metadata",
  Publish: "publish",
} as const;
export type Stage = ClosedEnum<typeof Stage>;

export type DeploymentLogEntry = {
  stage: Stage;
  level: string;
  message: string;
  timestamp: string;
  error?: DeploymentLogEntryError | undefined;
};

/** @internal */
export const Stage$inboundSchema: z.ZodNativeEnum<typeof Stage> = z.nativeEnum(
  Stage,
);

/** @internal */
export const DeploymentLogEntry$inboundSchema: z.ZodType<
  DeploymentLogEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  stage: Stage$inboundSchema,
  level: z.string(),
  message: z.string(),
  timestamp: z.string(),
  error: DeploymentLogEntryError$inboundSchema.optional(),
});

export function deploymentLogEntryFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentLogEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentLogEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentLogEntry' from JSON`,
  );
}
