/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeploymentLogEntryError = {
  message?: string | undefined;
};

/** @internal */
export const DeploymentLogEntryError$inboundSchema: z.ZodType<
  DeploymentLogEntryError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
});

export function deploymentLogEntryErrorFromJSON(
  jsonString: string,
): SafeParseResult<DeploymentLogEntryError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeploymentLogEntryError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeploymentLogEntryError' from JSON`,
  );
}
