/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ExceptionEntry = {
  timestamp: string;
  name: string;
  message: string;
  stack?: string | undefined;
};

/** @internal */
export const ExceptionEntry$inboundSchema: z.ZodType<
  ExceptionEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  timestamp: z.string(),
  name: z.string(),
  message: z.string(),
  stack: z.string().optional(),
});

export function exceptionEntryFromJSON(
  jsonString: string,
): SafeParseResult<ExceptionEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExceptionEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExceptionEntry' from JSON`,
  );
}
