/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserConfigResponse = {
  /**
   * The saved user configuration
   */
  config: { [k: string]: any };
};

/** @internal */
export const GetUserConfigResponse$inboundSchema: z.ZodType<
  GetUserConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  config: z.record(z.any()),
});

export function getUserConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserConfigResponse' from JSON`,
  );
}
