/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type HttpConnection = {
  type: "http";
  deploymentUrl: string;
  configSchema: { [k: string]: any };
};

/** @internal */
export const HttpConnection$inboundSchema: z.ZodType<
  HttpConnection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("http"),
  deploymentUrl: z.string(),
  configSchema: z.record(z.any()),
});

export function httpConnectionFromJSON(
  jsonString: string,
): SafeParseResult<HttpConnection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => HttpConnection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HttpConnection' from JSON`,
  );
}
