/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InvocationResponse = {
  status: number;
  outcome: string;
};

/** @internal */
export const InvocationResponse$inboundSchema: z.ZodType<
  InvocationResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.number(),
  outcome: z.string(),
});

export function invocationResponseFromJSON(
  jsonString: string,
): SafeParseResult<InvocationResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvocationResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvocationResponse' from JSON`,
  );
}
