/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InvocationRequest = {
  method: string;
  url: string;
};

/** @internal */
export const InvocationRequest$inboundSchema: z.ZodType<
  InvocationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  method: z.string(),
  url: z.string(),
});

export function invocationRequestFromJSON(
  jsonString: string,
): SafeParseResult<InvocationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvocationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvocationRequest' from JSON`,
  );
}
