/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InvocationDuration = {
  cpuMs: number;
  wallMs: number;
};

/** @internal */
export const InvocationDuration$inboundSchema: z.ZodType<
  InvocationDuration,
  z.ZodTypeDef,
  unknown
> = z.object({
  cpuMs: z.number(),
  wallMs: z.number(),
});

export function invocationDurationFromJSON(
  jsonString: string,
): SafeParseResult<InvocationDuration, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvocationDuration$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvocationDuration' from JSON`,
  );
}
