/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ExceptionEntry,
  ExceptionEntry$inboundSchema,
} from "./exceptionentry.js";
import {
  InvocationDuration,
  InvocationDuration$inboundSchema,
} from "./invocationduration.js";
import {
  InvocationRequest,
  InvocationRequest$inboundSchema,
} from "./invocationrequest.js";
import {
  InvocationResponse,
  InvocationResponse$inboundSchema,
} from "./invocationresponse.js";
import {
  RuntimeLogEntry,
  RuntimeLogEntry$inboundSchema,
} from "./runtimelogentry.js";

export type Invocation = {
  id: string;
  timestamp: string;
  request: InvocationRequest;
  response: InvocationResponse;
  duration: InvocationDuration;
  logs: Array<RuntimeLogEntry>;
  exceptions: Array<ExceptionEntry>;
};

/** @internal */
export const Invocation$inboundSchema: z.ZodType<
  Invocation,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  timestamp: z.string(),
  request: InvocationRequest$inboundSchema,
  response: InvocationResponse$inboundSchema,
  duration: InvocationDuration$inboundSchema,
  logs: z.array(RuntimeLogEntry$inboundSchema),
  exceptions: z.array(ExceptionEntry$inboundSchema),
});

export function invocationFromJSON(
  jsonString: string,
): SafeParseResult<Invocation, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Invocation$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Invocation' from JSON`,
  );
}
