/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type LogsQuery = {
  /**
   * Start of time range (ISO 8601).
   */
  from?: string | undefined;
  /**
   * End of time range (ISO 8601).
   */
  to?: string | undefined;
  /**
   * Max invocations to return. Defaults to 50.
   */
  limit?: number | undefined;
};

/** @internal */
export type LogsQuery$Outbound = {
  from?: string | undefined;
  to?: string | undefined;
  limit?: number | undefined;
};

/** @internal */
export const LogsQuery$outboundSchema: z.ZodType<
  LogsQuery$Outbound,
  z.ZodTypeDef,
  LogsQuery
> = z.object({
  from: z.string().optional(),
  to: z.string().optional(),
  limit: z.number().int().optional(),
});

export function logsQueryToJSON(logsQuery: LogsQuery): string {
  return JSON.stringify(LogsQuery$outboundSchema.parse(logsQuery));
}
