/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type Profile = {
  slug: string;
  displayName: string;
  description: string | null;
  type: string | null;
};

export type ProfilesResponsePagination = {
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
};

export type ProfilesResponse = {
  profiles: Array<Profile>;
  pagination: ProfilesResponsePagination;
};

/** @internal */
export const Profile$inboundSchema: z.ZodType<Profile, z.ZodTypeDef, unknown> =
  z.object({
    slug: z.string(),
    displayName: z.string(),
    description: z.nullable(z.string()),
    type: z.nullable(z.string()),
  });

export function profileFromJSON(
  jsonString: string,
): SafeParseResult<Profile, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Profile$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Profile' from JSON`,
  );
}

/** @internal */
export const ProfilesResponsePagination$inboundSchema: z.ZodType<
  ProfilesResponsePagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number(),
  pageSize: z.number(),
  totalCount: z.number(),
  totalPages: z.number(),
});

export function profilesResponsePaginationFromJSON(
  jsonString: string,
): SafeParseResult<ProfilesResponsePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfilesResponsePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfilesResponsePagination' from JSON`,
  );
}

/** @internal */
export const ProfilesResponse$inboundSchema: z.ZodType<
  ProfilesResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  profiles: z.array(z.lazy(() => Profile$inboundSchema)),
  pagination: z.lazy(() => ProfilesResponsePagination$inboundSchema),
});

export function profilesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProfilesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfilesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfilesResponse' from JSON`,
  );
}
