/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ProfileServersResponseServer = {
  slug: string;
  displayName: string;
  mcpUrl: string;
  description: string | null;
};

export type ProfileServersResponsePagination = {
  page: number;
  pageSize: number;
  totalCount: number;
  totalPages: number;
};

export type ProfileServersResponse = {
  servers: Array<ProfileServersResponseServer>;
  pagination: ProfileServersResponsePagination;
};

/** @internal */
export const ProfileServersResponseServer$inboundSchema: z.ZodType<
  ProfileServersResponseServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  slug: z.string(),
  displayName: z.string(),
  mcpUrl: z.string(),
  description: z.nullable(z.string()),
});

export function profileServersResponseServerFromJSON(
  jsonString: string,
): SafeParseResult<ProfileServersResponseServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfileServersResponseServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfileServersResponseServer' from JSON`,
  );
}

/** @internal */
export const ProfileServersResponsePagination$inboundSchema: z.ZodType<
  ProfileServersResponsePagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  page: z.number(),
  pageSize: z.number(),
  totalCount: z.number(),
  totalPages: z.number(),
});

export function profileServersResponsePaginationFromJSON(
  jsonString: string,
): SafeParseResult<ProfileServersResponsePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfileServersResponsePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfileServersResponsePagination' from JSON`,
  );
}

/** @internal */
export const ProfileServersResponse$inboundSchema: z.ZodType<
  ProfileServersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  servers: z.array(z.lazy(() => ProfileServersResponseServer$inboundSchema)),
  pagination: z.lazy(() => ProfileServersResponsePagination$inboundSchema),
});

export function profileServersResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProfileServersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProfileServersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProfileServersResponse' from JSON`,
  );
}
