/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ResumeResponse = {
  status: string;
  deploymentId: string;
};

/** @internal */
export const ResumeResponse$inboundSchema: z.ZodType<
  ResumeResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  deploymentId: z.string(),
});

export function resumeResponseFromJSON(
  jsonString: string,
): SafeParseResult<ResumeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResumeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResumeResponse' from JSON`,
  );
}
