/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type RuntimeLogEntry = {
  timestamp: string;
  level: string;
  message: string;
};

/** @internal */
export const RuntimeLogEntry$inboundSchema: z.ZodType<
  RuntimeLogEntry,
  z.ZodTypeDef,
  unknown
> = z.object({
  timestamp: z.string(),
  level: z.string(),
  message: z.string(),
});

export function runtimeLogEntryFromJSON(
  jsonString: string,
): SafeParseResult<RuntimeLogEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RuntimeLogEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RuntimeLogEntry' from JSON`,
  );
}
