/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type SaveUserConfigRequest = {
  /**
   * The user configuration to save
   */
  config: { [k: string]: any };
};

/** @internal */
export type SaveUserConfigRequest$Outbound = {
  config: { [k: string]: any };
};

/** @internal */
export const SaveUserConfigRequest$outboundSchema: z.ZodType<
  SaveUserConfigRequest$Outbound,
  z.ZodTypeDef,
  SaveUserConfigRequest
> = z.object({
  config: z.record(z.any()),
});

export function saveUserConfigRequestToJSON(
  saveUserConfigRequest: SaveUserConfigRequest,
): string {
  return JSON.stringify(
    SaveUserConfigRequest$outboundSchema.parse(saveUserConfigRequest),
  );
}
