/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SaveUserConfigResponse = {
  success: boolean;
  message?: string | undefined;
};

/** @internal */
export const SaveUserConfigResponse$inboundSchema: z.ZodType<
  SaveUserConfigResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  message: z.string().optional(),
});

export function saveUserConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<SaveUserConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaveUserConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaveUserConfigResponse' from JSON`,
  );
}
