/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServersListResponseServer = {
  qualifiedName: string;
  displayName: string | null;
  description: string | null;
  iconUrl: string | null;
  verified: boolean;
  useCount: number;
  remote: boolean;
  createdAt: string;
  homepage: string;
};

export type ServersListResponsePagination = {
  currentPage: number;
  pageSize: number;
  totalPages: number;
  totalCount: number;
};

export type ServersListResponse = {
  servers: Array<ServersListResponseServer>;
  pagination: ServersListResponsePagination;
};

/** @internal */
export const ServersListResponseServer$inboundSchema: z.ZodType<
  ServersListResponseServer,
  z.ZodTypeDef,
  unknown
> = z.object({
  qualifiedName: z.string(),
  displayName: z.nullable(z.string()),
  description: z.nullable(z.string()),
  iconUrl: z.nullable(z.string()),
  verified: z.boolean(),
  useCount: z.number(),
  remote: z.boolean(),
  createdAt: z.string(),
  homepage: z.string(),
});

export function serversListResponseServerFromJSON(
  jsonString: string,
): SafeParseResult<ServersListResponseServer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServersListResponseServer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServersListResponseServer' from JSON`,
  );
}

/** @internal */
export const ServersListResponsePagination$inboundSchema: z.ZodType<
  ServersListResponsePagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  currentPage: z.number(),
  pageSize: z.number(),
  totalPages: z.number(),
  totalCount: z.number(),
});

export function serversListResponsePaginationFromJSON(
  jsonString: string,
): SafeParseResult<ServersListResponsePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServersListResponsePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServersListResponsePagination' from JSON`,
  );
}

/** @internal */
export const ServersListResponse$inboundSchema: z.ZodType<
  ServersListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  servers: z.array(z.lazy(() => ServersListResponseServer$inboundSchema)),
  pagination: z.lazy(() => ServersListResponsePagination$inboundSchema),
});

export function serversListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServersListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServersListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServersListResponse' from JSON`,
  );
}
