/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServerSecurity = {
  scanPassed: boolean;
};

/** @internal */
export const ServerSecurity$inboundSchema: z.ZodType<
  ServerSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  scanPassed: z.boolean(),
});

export function serverSecurityFromJSON(
  jsonString: string,
): SafeParseResult<ServerSecurity, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerSecurity$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerSecurity' from JSON`,
  );
}
