/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServerSummary = {
  qualifiedName: string;
  displayName: string | null;
  description: string | null;
  iconUrl: string | null;
  verified: boolean;
  useCount: number;
  remote: boolean | null;
  isDeployed: boolean;
  createdAt: string;
  homepage: string;
};

/** @internal */
export const ServerSummary$inboundSchema: z.ZodType<
  ServerSummary,
  z.ZodTypeDef,
  unknown
> = z.object({
  qualifiedName: z.string(),
  displayName: z.nullable(z.string()),
  description: z.nullable(z.string()),
  iconUrl: z.nullable(z.string()),
  verified: z.boolean(),
  useCount: z.number(),
  remote: z.nullable(z.boolean()),
  isDeployed: z.boolean(),
  createdAt: z.string(),
  homepage: z.string(),
});

export function serverSummaryFromJSON(
  jsonString: string,
): SafeParseResult<ServerSummary, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerSummary$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerSummary' from JSON`,
  );
}
