/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  ToolInputSchema,
  ToolInputSchema$inboundSchema,
} from "./toolinputschema.js";

export type ServerTool = {
  name: string;
  description: string | null;
  inputSchema: ToolInputSchema;
};

/** @internal */
export const ServerTool$inboundSchema: z.ZodType<
  ServerTool,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  description: z.nullable(z.string()),
  inputSchema: ToolInputSchema$inboundSchema,
});

export function serverToolFromJSON(
  jsonString: string,
): SafeParseResult<ServerTool, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServerTool$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServerTool' from JSON`,
  );
}
