/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type ServersListQuery = {
  page?: number | undefined;
  pageSize?: number | undefined;
  q?: string | undefined;
};

/** @internal */
export type ServersListQuery$Outbound = {
  page?: number | undefined;
  pageSize?: number | undefined;
  q?: string | undefined;
};

/** @internal */
export const ServersListQuery$outboundSchema: z.ZodType<
  ServersListQuery$Outbound,
  z.ZodTypeDef,
  ServersListQuery
> = z.object({
  page: z.number().int().optional(),
  pageSize: z.number().int().optional(),
  q: z.string().optional(),
});

export function serversListQueryToJSON(
  serversListQuery: ServersListQuery,
): string {
  return JSON.stringify(
    ServersListQuery$outboundSchema.parse(serversListQuery),
  );
}
