/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ServersListResponse = {};

/** @internal */
export const ServersListResponse$inboundSchema: z.ZodType<
  ServersListResponse,
  z.ZodTypeDef,
  unknown
> = z.object({});

export function serversListResponseFromJSON(
  jsonString: string,
): SafeParseResult<ServersListResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ServersListResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ServersListResponse' from JSON`,
  );
}
