/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import {
  HttpConnection,
  HttpConnection$inboundSchema,
} from "./httpconnection.js";
import {
  ServerSecurity,
  ServerSecurity$inboundSchema,
} from "./serversecurity.js";
import { ServerTool, ServerTool$inboundSchema } from "./servertool.js";
import {
  StdioConnection,
  StdioConnection$inboundSchema,
} from "./stdioconnection.js";

export type Connection = StdioConnection | HttpConnection;

export type Server = {
  qualifiedName: string;
  displayName: string;
  description: string;
  iconUrl: string | null;
  remote: boolean;
  deploymentUrl: string | null;
  connections: Array<StdioConnection | HttpConnection>;
  security: ServerSecurity | null;
  tools: Array<ServerTool> | null;
};

/** @internal */
export const Connection$inboundSchema: z.ZodType<
  Connection,
  z.ZodTypeDef,
  unknown
> = z.union([StdioConnection$inboundSchema, HttpConnection$inboundSchema]);

export function connectionFromJSON(
  jsonString: string,
): SafeParseResult<Connection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Connection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Connection' from JSON`,
  );
}

/** @internal */
export const Server$inboundSchema: z.ZodType<Server, z.ZodTypeDef, unknown> = z
  .object({
    qualifiedName: z.string(),
    displayName: z.string(),
    description: z.string(),
    iconUrl: z.nullable(z.string()),
    remote: z.boolean(),
    deploymentUrl: z.nullable(z.string()),
    connections: z.array(
      z.union([StdioConnection$inboundSchema, HttpConnection$inboundSchema]),
    ),
    security: z.nullable(ServerSecurity$inboundSchema),
    tools: z.nullable(z.array(ServerTool$inboundSchema)),
  });

export function serverFromJSON(
  jsonString: string,
): SafeParseResult<Server, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Server$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Server' from JSON`,
  );
}
