/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type StdioConnection = {
  type: "stdio";
  bundleUrl?: string | undefined;
  runtime?: string | undefined;
  stdioFunction?: string | undefined;
  configSchema: { [k: string]: any };
};

/** @internal */
export const StdioConnection$inboundSchema: z.ZodType<
  StdioConnection,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("stdio"),
  bundleUrl: z.string().optional(),
  runtime: z.string().optional(),
  stdioFunction: z.string().optional(),
  configSchema: z.record(z.any()),
});

export function stdioConnectionFromJSON(
  jsonString: string,
): SafeParseResult<StdioConnection, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => StdioConnection$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'StdioConnection' from JSON`,
  );
}
