/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ToolInputSchema = {
  type: "object";
  properties?: { [k: string]: any } | undefined;
};

/** @internal */
export const ToolInputSchema$inboundSchema: z.ZodType<
  ToolInputSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: z.literal("object"),
  properties: z.record(z.any()).optional(),
});

export function toolInputSchemaFromJSON(
  jsonString: string,
): SafeParseResult<ToolInputSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ToolInputSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ToolInputSchema' from JSON`,
  );
}
