/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UplinkTokenResponse = {
  authtoken: string;
  domain: string;
};

/** @internal */
export const UplinkTokenResponse$inboundSchema: z.ZodType<
  UplinkTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  authtoken: z.string(),
  domain: z.string(),
});

export function uplinkTokenResponseFromJSON(
  jsonString: string,
): SafeParseResult<UplinkTokenResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UplinkTokenResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UplinkTokenResponse' from JSON`,
  );
}
