/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configGet } from "../funcs/configGet.js";
import { configGetStatus } from "../funcs/configGetStatus.js";
import { configUpdate } from "../funcs/configUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Config extends ClientSDK {
  /**
   * Get configuration status
   *
   * @remarks
   * Check if user has all required configuration fields for a server without exposing actual values. Optionally specify profile with ?profile=qualified-name query parameter.
   */
  async getStatus(
    request: operations.GetConfigStatusByIdRequest,
    options?: RequestOptions,
  ): Promise<components.ConfigValidationResponse> {
    return unwrapAsync(configGetStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Get saved user configuration for a server
   *
   * @remarks
   * Retrieve the saved user configuration for a specific server. Optionally specify profile with ?profile=qualified-name query parameter.
   */
  async get(
    request: operations.GetConfigByIdRequest,
    options?: RequestOptions,
  ): Promise<components.GetUserConfigResponse> {
    return unwrapAsync(configGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Save user configuration for a server
   *
   * @remarks
   * Save user configuration for a specific server to be used in future connections. Optionally specify profile with ?profile=qualified-name query parameter.
   */
  async update(
    request: operations.PutConfigByIdRequest,
    options?: RequestOptions,
  ): Promise<components.SaveUserConfigResponse> {
    return unwrapAsync(configUpdate(
      this,
      request,
      options,
    ));
  }
}
