/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { profilesAddServer } from "../funcs/profilesAddServer.js";
import { profilesDeleteServer } from "../funcs/profilesDeleteServer.js";
import { profilesGetServer } from "../funcs/profilesGetServer.js";
import { profilesList } from "../funcs/profilesList.js";
import { profilesListServers } from "../funcs/profilesListServers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Profiles extends ClientSDK {
  /**
   * List user profiles
   */
  async list(
    request: operations.GetProfilesRequest,
    options?: RequestOptions,
  ): Promise<components.ProfilesResponse> {
    return unwrapAsync(profilesList(
      this,
      request,
      options,
    ));
  }

  /**
   * List MCP servers for a profile
   */
  async listServers(
    request: operations.GetProfilesBySlugServersRequest,
    options?: RequestOptions,
  ): Promise<components.ProfileServersResponse> {
    return unwrapAsync(profilesListServers(
      this,
      request,
      options,
    ));
  }

  /**
   * Save a server to a profile
   */
  async addServer(
    request: operations.PostProfilesBySlugServersRequest,
    options?: RequestOptions,
  ): Promise<operations.PostProfilesBySlugServersResponse> {
    return unwrapAsync(profilesAddServer(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a profile server
   */
  async getServer(
    request: operations.GetProfilesBySlugServersByConfigSlugRequest,
    options?: RequestOptions,
  ): Promise<operations.GetProfilesBySlugServersByConfigSlugResponse> {
    return unwrapAsync(profilesGetServer(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a profile server
   */
  async deleteServer(
    request: operations.DeleteProfilesBySlugServersByConfigSlugRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(profilesDeleteServer(
      this,
      request,
      options,
    ));
  }
}
