/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Servers } from "./servers.js";
import { Service } from "./service.js";
import { Uplink } from "./uplink.js";

export class SmitheryRegistry extends ClientSDK {
  private _service?: Service;
  get service(): Service {
    return (this._service ??= new Service(this._options));
  }

  private _servers?: Servers;
  get servers(): Servers {
    return (this._servers ??= new Servers(this._options));
  }

  private _uplink?: Uplink;
  get uplink(): Uplink {
    return (this._uplink ??= new Uplink(this._options));
  }
}
