/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversDeploy } from "../funcs/serversDeploy.js";
import { serversGetByQualifiedName } from "../funcs/serversGetByQualifiedName.js";
import { serversGetDeploymentStatus } from "../funcs/serversGetDeploymentStatus.js";
import { serversGetLogs } from "../funcs/serversGetLogs.js";
import { serversList } from "../funcs/serversList.js";
import { serversListDeployments } from "../funcs/serversListDeployments.js";
import { serversResumeDeployment } from "../funcs/serversResumeDeployment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Servers extends ClientSDK {
  /**
   * Deploy an MCP server
   *
   * @remarks
   * Upload and deploy an MCP server (hosted or external)
   */
  async deploy(
    request: operations.PutServersByQualifiedNameDeploymentsRequest,
    options?: RequestOptions,
  ): Promise<components.DeployResponse> {
    return unwrapAsync(serversDeploy(
      this,
      request,
      options,
    ));
  }

  /**
   * List deployments for a server
   */
  async listDeployments(
    request: operations.GetServersByQualifiedNameDeploymentsRequest,
    options?: RequestOptions,
  ): Promise<Array<any>> {
    return unwrapAsync(serversListDeployments(
      this,
      request,
      options,
    ));
  }

  /**
   * Get deployment status
   */
  async getDeploymentStatus(
    request: operations.GetServersByQualifiedNameDeploymentsByIdRequest,
    options?: RequestOptions,
  ): Promise<components.DeploymentInfo> {
    return unwrapAsync(serversGetDeploymentStatus(
      this,
      request,
      options,
    ));
  }

  /**
   * Resume a paused deployment workflow (e.g., after OAuth authorization)
   *
   * @remarks
   * Use id='latest' to resume the most recent deployment
   */
  async resumeDeployment(
    request: operations.PostServersByQualifiedNameDeploymentsByIdResumeRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(serversResumeDeployment(
      this,
      request,
      options,
    ));
  }

  /**
   * Get runtime logs for a server
   *
   * @remarks
   * Fetch recent runtime logs for the server's deployed Worker, grouped by invocation (requires ownership).
   */
  async getLogs(
    request: operations.GetServersByQualifiedNameLogsRequest,
    options?: RequestOptions,
  ): Promise<components.RuntimeLogsResponse> {
    return unwrapAsync(serversGetLogs(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a server by qualified name
   *
   * @remarks
   * Get a single server by its qualified name. The qualified name can be either 'name' (unnamespaced) or 'namespace/name' (namespaced).
   */
  async getByQualifiedName(
    request: operations.GetServersByQualifiedNameRequest,
    options?: RequestOptions,
  ): Promise<components.Server> {
    return unwrapAsync(serversGetByQualifiedName(
      this,
      request,
      options,
    ));
  }

  /**
   * List all servers
   *
   * @remarks
   * Get a paginated list of all servers
   */
  async list(
    request: operations.GetServersRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetServersResponse, { page: number }>> {
    return unwrapResultIterator(serversList(
      this,
      request,
      options,
    ));
  }
}
