/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversConfigure } from "../funcs/serversConfigure.js";
import { serversGet } from "../funcs/serversGet.js";
import { serversList } from "../funcs/serversList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Servers extends ClientSDK {
  /**
   * List all servers
   *
   * @remarks
   * Get a paginated list of all servers
   */
  async list(
    request: operations.GetServersRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.GetServersResponse, { page: number }>> {
    return unwrapResultIterator(serversList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a server by ID
   *
   * @remarks
   * Get a single server by its qualified name or ID
   */
  async get(
    request: operations.GetServersByIdRequest,
    options?: RequestOptions,
  ): Promise<components.Server> {
    return unwrapAsync(serversGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Generate server configuration
   *
   * @remarks
   * Generate configuration for instantiating a server connection
   */
  async configure(
    request: operations.PostServersByIdRequest,
    options?: RequestOptions,
  ): Promise<components.ConfigResponse> {
    return unwrapAsync(serversConfigure(
      this,
      request,
      options,
    ));
  }
}
