/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serviceHealthCheck } from "../funcs/serviceHealthCheck.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Service extends ClientSDK {
  /**
   * Health check
   *
   * @remarks
   * Check if the service is running
   */
  async healthCheck(
    options?: RequestOptions,
  ): Promise<components.Health> {
    return unwrapAsync(serviceHealthCheck(
      this,
      options,
    ));
  }
}
