/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { uplinkCreateToken } from "../funcs/uplinkCreateToken.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Uplink extends ClientSDK {
  /**
   * Create uplink token
   *
   * @remarks
   * Create or retrieve an authtoken for uplink connections
   */
  async createToken(
    options?: RequestOptions,
  ): Promise<components.UplinkTokenResponse> {
    return unwrapAsync(uplinkCreateToken(
      this,
      options,
    ));
  }
}
