workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Smithery Registry API:
        inputs:
            - location: ../../openapi/registry.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/smithery-lhr/smithery/smithery-registry-api
targets:
    smithery-registry:
        target: typescript
        source: Smithery Registry API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/smithery-lhr/smithery/smithery-registry-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
