name: Publish Python SDK to PyPI

on:
  push:
    branches:
      - main
    paths:
      - 'python/pyproject.toml'  # Only trigger on version changes
  workflow_dispatch:  # Allows manual triggering

concurrency:
  group: py-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        working-directory: python

    steps:
      - uses: actions/checkout@v3
      
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"
          
      - name: Install dependencies
        run: uv sync
        
      - name: Run tests
        run: uv run pytest -v --tb=short
        
      - name: Run linter
        run: uv run ruff check --fix
        
      - name: Build package
        run: uv build
        
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/