/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversGet } from "../../funcs/serversGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetServerRequest$inboundSchema,
};

export const tool$serversGet: ToolDefinition<typeof args> = {
  name: "servers-get",
  description: `Get Server

Retrieves detailed information about a specific server by its qualified name.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
