/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { serversList } from "../../funcs/serversList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListServersRequest$inboundSchema,
};

export const tool$serversList: ToolDefinition<typeof args> = {
  name: "servers-list",
  description: `List Servers

Retrieves a paginated list of all available servers with optional filtering.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await serversList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value.result;

    return formatResult(value, apiCall);
  },
};
